source:
  repoURL: https://helm.traefik.io/traefik
  chart: traefik
  targetRevision: "34.0.0"
  helm:
    releaseName: traefik
    valueFiles:
      - $values/vixens-gitops/apps/traefik/values.yaml
- repoURL: https://github.com/charchess/configs.git
  targetRevision: gitops
  ref: values