# apps/traefik/values.yaml
service:
  type: LoadBalancer
  loadBalancerIP: "192.168.200.70"
  annotations:
    metallb.universe.tf/address-pool: ingress-pool   # ← force le pool
#ports:
#  web:
#    port: 80
#    targetPort: 80
#  websecure:
#    port: 443
#    targetPort: 443

additionalArguments:
  - --providers.kubernetescrd.allowExternalNameServices=true


dashboard:
  enabled: true
    
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
    
  