
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pvc-databases-neo4j-data
  labels:
    stack: databases
    container: neo4j
    volume: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: jade
    path: /data/nfs/containers/databases/neo4j/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pvc-databases-qdrant-data
  labels:
    stack: databases
    container: qdrant
    volume: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: jade
    path: /data/nfs/containers/databases/qdrant/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pvc-databases-redis-data
  labels:
    stack: databases
    container: redis
    volume: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: jade
    path: /data/nfs/containers/databases/redis/data

