apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.6.0
    helm:
      values: |
        global:
          cattle:
            systemDefaultRegistry: ""
        preUpgradeChecker:
          enabled: false  # ← Désactive complètement
        
        defaultSettings:
          createDefaultDiskLabeledNodes: true
          defaultDataPath: /var/lib/longhorn
          replicaSoftAntiAffinity: false
          storageOverProvisioningPercentage: 200
          storageMinimalAvailablePercentage: 25
        
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
        
        ingress:
          enabled: false
        
        service:
          ui:
            type: ClusterIP
        
        longhornManager:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          securityContext:
            privileged: true
        
        longhornDriver:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          securityContext:
            privileged: true
        
        csi:
          attacherReplicaCount: 2
          provisionerReplicaCount: 2
          resizerReplicaCount: 2
          snapshotterReplicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
