# vixens-gitops/apps/longhorn/ingress.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui-https
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.truxonline.com`)
      kind: Rule
      services:
        - name: longhorn-ui
          port: 80
  tls:
    certResolver: le