# Active et configure l'Ingress pour l'interface utilisateur
ingress:
  enabled: true
  ingressClassName: "traefik"
  host: longhorn.truxonline.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-gandi-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"

# AJOUTE LES TOLÉRANCES NÉCESSAIRES POUR VOS NŒUDS CONTROL-PLANE
# Le chart de Longhorn appliquera cette configuration à tous ses composants.
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"