apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: databases
  name: pvc-databases-redis-data
  labels:
    stack: databases
    container: redis
    volume: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-databases-redis-data
