apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: experimentations
  name: pvc-experimentations-puppet-ssl
  labels:
    stack: experimentations
    container: puppet
    volume: ssl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-experimentations-puppet-ssl
