apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: experimentations
  name: pvc-experimentations-zabbix-export
  labels:
    stack: experimentations
    container: zabbix
    volume: export
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-experimentations-zabbix-export
