apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ai_services
  name: pvc-ai_services-chat-ui-.git
  labels:
    stack: ai_services
    container: chat-ui
    volume: .git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-ai_services-chat-ui-.git
