apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  name: pvc-infrastructure-traefik-config
  labels:
    stack: infrastructure
    container: traefik
    volume: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-infrastructure-traefik-config
