apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: https://github.com/charchess/configs.git
      targetRevision: HEAD
      path: vixens-gitops/apps/argocd/helm-chart
      helm:
        valueFiles:
          - $values/vixens-gitops/apps/argocd/helm-values.yaml
    # Dépôt Git pour les manifestes manuels
    - repoURL: https://github.com/charchess/configs.git
      targetRevision: gitops
      path: vixens-gitops/apps/argocd/manifests

  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      