configs:
  secret:
    redis:
      job:
        nodeSelector: {}
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"