apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: experimentations
  name: pvc-experimentations-hydra2-downloads
  labels:
    stack: experimentations
    container: hydra2
    volume: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-experimentations-hydra2-downloads
