apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: experimentations
  name: pvc-experimentations-nginx-letsencrypt
  labels:
    stack: experimentations
    container: nginx
    volume: letsencrypt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-experimentations-nginx-letsencrypt
