apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: databases
  name: pvc-databases-qdrant-data
  labels:
    stack: databases
    container: qdrant
    volume: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-databases-qdrant-data
