apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: experimentations
  name: pvc-experimentations-samba-shares
  labels:
    stack: experimentations
    container: samba
    volume: shares
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: pv-pvc-experimentations-samba-shares
