# manifests/argocd-redis-secret.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-redis
  namespace: argocd
type: Opaque
stringData:
#  redis-password: "argocd-redis-pw"
  auth: "argocd-redis-pw"
    