# Fichier : manifests/cert-manager-webhook-gandi-rbac-final.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gandi-webhook-authentication-reader
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["extension-apiserver-authentication"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gandi-webhook-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gandi-webhook-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook-gandi
  namespace: cert-manager