# manifests/cert-manager-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gandi-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: charchess@truxonline.com
    privateKeySecretRef:
      name: letsencrypt-gandi-prod-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.bwolf.me
          solverName: gandi
          config:
            patSecretRef:          # ← not apiKeySecretRef
              name: gandi-credentials
              key: pat             # ← must be “pat”