apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.bwolf.me
  labels:
    app: cert-manager-webhook-gandi
spec:
  group: acme.bwolf.me
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-gandi
    namespace: cert-manager
  version: v1alpha1
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRhZ0F3SUJBZ0lRSUd2alF2Y1dCajBQeEJpdHg5cXh4akFLQmdncWhrak9QUVFEQWpBb01TWXcKSkFZRFZRUURFeDFqWlhKMExXMWhibUZuWlhJdGQyVmlhRzl2YXkxbllXNWthUzFqWVRBZUZ3MHlOVEE0TWpBdwpPRE0wTlROYUZ3MHlOVEV4TVRnd09ETTBOVE5hTUNneEpqQWtCZ05WQkFNVEhXTmxjblF0YldGdVlXZGxjaTEzClpXSm9iMjlyTFdkaGJtUnBMV05oTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNFhOVnBYTisKbmdBWENqbHRrSkVHRDJ2UlpDSjBUbHZlbmJqOFVSaW50Q0JjOWxRZmFiWkpQbUpqQXA0RklVZmdnU0tUdGdxNgphdWxYVjNzRU0zL1FBNk5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkhRWURWUjBPQkJZRUZBcjVJNmtGcGJGejdqTnZhaUFsY0RMY1pTNGtNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUMKSVFEMmpERTY3L2xoQ3RwNWNBdE5YMFJrMExyYjFxNldaSWh3N3pXdlNiU1U2Z0lnU3ZGc0p3VWxhYmZnNnQweApYNDdqYU9MdHZ4K0V6QTRsN1Z2WC9VWFhMLzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  