# Fichier: manifests/cert-manager-to-kube-api.yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-cert-manager-to-kube-api
  namespace: cert-manager
spec:
  # Appliquer cette politique à tous les pods du namespace cert-manager
  endpointSelector: {}
  # Autoriser le trafic sortant (egress)
  egress:
  # Vers les endpoints de kube-apiserver
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-apiserver
    toPorts:
    - ports:
      - port: "6443"
        protocol: TCP
  # Vers le service ClusterIP de l'API Server
  - toServices:
    - k8sService:
        serviceName: kubernetes
        namespace: default