# Fichier : manifests/cert-manager-webhook-gandi.yaml (version finale)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-gandi
  namespace: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-gandi
  namespace: cert-manager
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: cert-manager-webhook-gandi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-gandi-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: cert-manager-webhook-gandi-ca
  secretName: cert-manager-webhook-gandi-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-gandi-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: cert-manager-webhook-gandi-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-gandi-tls
  namespace: cert-manager
spec:
  secretName: cert-manager-webhook-gandi-tls
  duration: 8760h
  renewBefore: 360h
  dnsNames:
  - cert-manager-webhook-gandi
  - cert-manager-webhook-gandi.cert-manager
  - cert-manager-webhook-gandi.cert-manager.svc
  issuerRef:
    name: cert-manager-webhook-gandi-issuer
    kind: Issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-gandi
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook-gandi
  template:
    metadata:
      labels:
        app: cert-manager-webhook-gandi
    spec:
      serviceAccountName: cert-manager-webhook-gandi
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: webhook
        image: ghcr.io/sintef/cert-manager-webhook-gandi:main
        env:
        - name: GROUP_NAME
          value: acme.bwolf.me
        ports:
        - containerPort: 8443
          name: https
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: cert-manager-webhook-gandi-tls
