# manifests//cert-manager-values.yaml
crds:
  enabled: true
  
extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53

# Tolérances globales pour tous les composants
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

# Tolérances spécifiques si la globale ne suffit pas
webhook:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

cainjector:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

startupapicheck:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"