# Source: cilium/templates/cilium-helm-chart.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
# Source: cilium/templates/cilium-helm-chart.yaml
apiVersion: helm.talos.dev/v1alpha1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart: oci://ghcr.io/cilium/charts/cilium
  version: 1.15.5
  values: |
    operator:
      replicas: 1
    kubeProxyReplacement: "true"
    k8sServiceHost: 192.168.1.45
    k8sServicePort: 6443
    bpf:
      masquerade: true
    ipam:
      mode: "kubernetes"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
