# manifests/cilium-values.yaml
#directRoutingDevice: enp2s0.200,enp3s0.200
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
    - 10.244.0.0/16
k8sServiceHost: 192.168.111.60
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  replicas: 1
securityContext:
  privileged: true
#directRoutingDevice: "enp2s0.200,enp3s0.200"
#tunnel: vxlan
routingMode: tunnel # C'est le nom correct du paramètre dans le chart
#enableIPv4Masquerade: true # Assure-toi que c'est bien à true
# AJOUTE CE BLOC POUR FORCER LE SNAT SUR LE TUNNEL
bpf:
  masquerade: true

hubble:
  enabled: true
  ui:
    enabled: true
    tolerations:                      # <-- ajout
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
  relay:
    enabled: true
    tolerations:                      # <-- même chose pour relay si tu veux
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"