# manifests/gandi-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gandi-credentials
  namespace: cert-manager
type: Opaque
data:
  pat: NDJhMmExYzU2ZTI5YmJmZjM5MTM0NWVhZmU4MTFlMmUwM2JhMDU4Ng==
