    apiVersion: "cilium.io/v2"
    kind: CiliumNetworkPolicy
    metadata:
      name: hubble-relay-policy
      namespace: kube-system
    spec:
      endpointSelector:
        matchLabels:
          k8s-app: hubble-relay
      egress:
      # Règle N°1 : Autoriser la communication avec le DNS (CoreDNS)
      - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
        toPorts:
        - ports:
          - port: "53"
            protocol: ANY
      # Règle N°2 : Autoriser la communication avec le service hubble-peer
      # Le service hubble-peer pointe vers les agents cilium.
      - toServices:
        - k8sService:
            serviceName: hubble-peer
            namespace: kube-system
    