apiVersion: v1
data:
  config.yaml: "cluster-name: default\npeer-service: \"hubble-peer.kube-system.svc.cluster.local.:80\"\nlisten-address:
    :4245\ngops: true\ngops-port: \"9893\"\nretry-timeout: \nsort-buffer-len-max:
    \nsort-buffer-drain-timeout: \ndisable-client-tls: true\n\ndisable-server-tls:
    true\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"cluster-name: default\npeer-service: \"hubble-peer.kube-system.svc.cluster.local.:80\"\nlisten-address: :4245\ngops: true\ngops-port: \"9893\"\nretry-timeout: \nsort-buffer-len-max: \nsort-buffer-drain-timeout: \ndisable-client-tls: true\n\ndisable-server-tls: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"hubble-relay-config","namespace":"kube-system"}}
  creationTimestamp: "2025-08-17T22:36:53Z"
  name: hubble-relay-config
  namespace: kube-system
  resourceVersion: "400874"
  uid: ef41bb1d-4ac1-42a7-93d2-91bfa0ba0e05
