# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
# CRDs (il y en a plusieurs, ici l’essentiel résumé)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ipaddresspools.metallb.io
spec:
  group: metallb.io
  names:
    kind: IPAddressPool
    listKind: IPAddressPoolList
    plural: ipaddresspools
    singular: ipaddresspool
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: l2advertisements.metallb.io
spec:
  group: metallb.io
  names:
    kind: L2Advertisement
    listKind: L2AdvertisementList
    plural: l2advertisements
    singular: l2advertisement
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
# Deployment controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: controller
  template:
    metadata:
      labels:
        component: controller
    spec:
      containers:
        - name: controller
          image: quay.io/metallb/controller:v0.14.5
          args:
            - --port=7472
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"      - --config=metallb
            
---
# DaemonSet speaker
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      component: speaker
  template:
    metadata:
      labels:
        component: speaker
    spec:
      containers:
        - name: speaker
          image: quay.io/metallb/speaker:v0.14.5
          args:
            - --port=7472
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
---
# IPAddressPool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-lan-200
  namespace: metallb-system
spec:
  addresses:
    - 192.168.200.70-192.168.200.79
---
# L2Advertisement
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adv-lan-200
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool-lan-200
    