# 01-metallb-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: metallb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: speaker
  namespace: metallb-system
  
  
# 02-metallb-l2.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-lan-200
  namespace: metallb-system
spec:
  addresses:
    - 192.168.200.70-192.168.200.79
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adv-lan-200
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool-lan-200