global:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
configs:
  params:
    server.insecure: true
server:
  service:
    ports:
      - name: http
        port: 80
        targetPort: 8080
redis:
  secretInit:
    job:
      enabled: false
      
      